### ISSUE TITLE
Detailed text prompt for PIE-Bench

### ISSUE THREAD

**Issue by Null-0000** [GiilDe/turbo-edit#3]
Hi! I'm trying to reproduce your results on the PIE-Bench. Do you have the plan for releasing the detailed text prompts for PIE-Bench? Thx.

**Comment by GiilDe** [comment]
Hi, we didn't run on the PIE-Bench in this work so I don't have any prompts for it, apologies. (though it seems that the PIE-Bench already has the source & target prompts so I'm not sure if I understood your question correctly :) )

**Comment by Null-0000** [comment]
Oh! Sorry. I have confused your work with another TurboEdit (TurboEdit: Instant text-based image editing). ==
