### ISSUE TITLE
The question about inference.

### ISSUE THREAD

**Issue by tttao-uwu** [GiilDe/turbo-edit#4]
Hello, thanks to your excellent work.
I have a question about editing. I noticed that in line 131 of main.py, after src_prompt and tgt prompt are input to pipeline, the edited image is generated. From my understanding, whether the whole editing process depends on pipeline.__call__.Is this __call__ function different from the previous standard stable diffusion__call__ function?

**Comment by GiilDe** [comment]
Hi, thank you very much!
You understand correctly. 
The '''__call__''' function is identical to the regular ''' __call__''' function, it is unchanged. The difference is because the scheduler's '''step ''' function is changed (it is called inside the '''__call__''' function)

**Comment by tttao-uwu** [comment]
> Hi, thank you very much! You understand correctly. The '''**call**''' function is identical to the regular ''' **call**''' function, it is unchanged. The difference is because the scheduler's '''step ''' function is changed (it is called inside the '''**call**''' function)

Thank you.
